### PR TITLE
Preserve case for env keys

### PR DESCRIPTION
**Pull request by thrawny**

### CODE REVIEW

**Comment by ourbjorn** [comment]
Thanks for the PR!

The `EnvParser` is implemented to explicitly allow for case insensitivity when parsing environment variables. If this PR were to be merged, it would result in a breaking change (I am one relying on the case insensitivity myself).

I would recommend creating a new parser (something like `CaseSensitiveEnvParser`?) instead. It could of course be accompanied by a new functional option to ease the use of it.

**Comment by thrawny** [comment]
> Thanks for the PR!
> 
> The `EnvParser` is implemented to explicitly allow for case insensitivity when parsing environment variables. If this PR were to be merged, it would result in a breaking change (I am one relying on the case insensitivity myself).
> 
> I would recommend creating a new parser (something like `CaseSensitiveEnvParser`?) instead. It could of course be accompanied by a new functional option to ease the use of it.

We are mixing `withEnv` and `withFile`, and `withFile` does preserve case which makes things somewhat confusing. You then have to know if a var is coming from env or a file in order to know what case to use.

```go
bind := binder.New(binder.WithEnv(),
  binder.WithFile("../../.secrets", ":"),
  binder.WithFile(".secrets", ":"),
  binder.WithFile("/etc/secrets/.secrets", ":"))
```

But point taken, I will add a case insensitive version

**Comment by ourbjorn** [comment]
Yeah, I get the confusion. And I was also somewhat wrong about the case insensitivity - since the current implementation is _forcing_ lower case configuration keys (for the struct tag `config:`). It is not case insensitive at all.

The changes made to `EnvParser` to force lower case are, in retrospect, completely wrong.

And maybe we're attacking this from the wrong end. It should be possible to read configuration values with case insensitivity or without it - but it shouldn't be up to the parsers. It should be up to `Binder` to do that interpretation.

Might be time for a v2, after all...

**Comment by thrawny** [comment]
Sounds like a good idea to make reading case insensitive by default, or at least offer that behaviour. Will revert to using the old lib for now.

**Pull request closed without merging**
